name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: Brank8
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Commit and Push changes to output branch
        run: |
          git checkout output
          git add dist/
          git commit -m "Update GitHub contributions" || exit 0
          git push origin HEAD:output

      - name: Merge changes to main branch
        run: |
          git checkout main
          git merge output
          git push origin HEAD:main
